---
version: "3"
services:
  napari-env:
    image: gnasello/napari-env:2023-10-07
    container_name: napari-env
    security_opt:
      - seccomp:unconfined # for terminal to work
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      #- SUBFOLDER=/ #optional
      - TITLE=Napari #optional
    #volumes:
      #- /path/to/directory:/config/researcher_home
      #- /var/run/docker.sock:/var/run/docker.sock #optional
    ports:
      - 3000:3000
    #devices:
      #- /dev/dri:/dev/dri #optional
    shm_size: "1gb" #optional