version: '3'

services:
  datascience:
    image: gnasello/napari-env:2023-06-29
    build: .
    ports:
      - $JLPORT:$JLPORT
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
    hostname: $HOST_NAME
    environment:
       - JLPORT=${JLPORT}
       - HOME_RESEARCHER=${HOME_RESEARCHER}
       - HOST_NAME=${HOST_NAME}
       - DISPLAY=0